version: "3.9"
services:
  web:
    image: fincht96/ci_cd_test_project:latest
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
